### ISSUE TITLE
Navbar underline in accordance to page visited not working in production mode

### ISSUE THREAD

**Issue by PapayaHUANG** [linju-podcast/website#13]
![image](https://github.com/linju-podcast/website/assets/70144378/9b49612b-efea-4400-88db-7258ddb8e11c)

It works well in dev mode, see the comparison logic blow:
https://github.com/linju-podcast/website/blob/e65f9811056e03128d5297a23c0cb34724fe2e88/src/components/style/Link.astro#L9-L15

**Comment by S1ngS1ng** [comment]
## Dev

<img width="1104" alt="image" src="https://github.com/linju-podcast/website/assets/13592559/b1ba27a2-4362-47fc-9cfa-cebfa97313cd">

## Production

<img width="1262" alt="image" src="https://github.com/linju-podcast/website/assets/13592559/1202acac-958f-4335-b97e-23d8bb9871fc">

**Comment by PapayaHUANG** [comment]
> ## Dev
> <img alt="image" width="1104" src="https://user-images.githubusercontent.com/13592559/274159616-b1ba27a2-4362-47fc-9cfa-cebfa97313cd.png">
> ## Production
> <img alt="image" width="1262" src="https://user-images.githubusercontent.com/13592559/274159664-1202acac-958f-4335-b97e-23d8bb9871fc.png">

原来如此，那为什么啊？
为了修复这个问题，我应该在把 currentPath 后面这个 `/` 去掉吗？还是写个判断，如果后面有 `/` 就去掉？

**Comment by S1ngS1ng** [comment]
> > ## Dev
> > <img alt="image" width="1104" src="https://user-images.githubusercontent.com/13592559/274159616-b1ba27a2-4362-47fc-9cfa-cebfa97313cd.png">
> > ## Production
> > <img alt="image" width="1262" src="https://user-images.githubusercontent.com/13592559/274159664-1202acac-958f-4335-b97e-23d8bb9871fc.png">
> 
> 原来如此，那为什么啊？ 为了修复这个问题，我应该在把 currentPath 后面这个 `/` 去掉吗？还是写个判断，如果后面有 `/` 就去掉？

AFAIC, Root cause 其实是 `translatePath` 的参数传的不对。`currentPath` 来自 Astro，但 `translatePath` 的 parameter 是我们自己写的
还有就是获取 `pathname` 的方式，应该用 `Astro.url.pathname`

See: #16
